### ISSUE TITLE
instance attr is not required for initializers

### ISSUE THREAD

**Issue by markokr** [stampit-org/stamp-specification#31] opened 2015-09-25 16:04 UTC
> Initializers have the following signature:
> (options, { instance, stamp }) => instance

Instance should be passed as "this" so not needed there.  this makes possible to lose the extra object altogether:

initializer(options, stamp)

**Comment by troutowicz** [comment] 2015-09-25 16:33
The initializer signature is handled internally. `instance` is an optional property that can be passed to a stamp, and as a result gets passed to initializers during initialization. It is up to the developer to write initializers to use the passed in `instance` if that is desired.

**Comment by markokr** [comment] 2015-09-25 16:59
From my reading it's signature for user initializers.  Those should be kept simple.

So I don't get what you mean by "internally".

**Comment by troutowicz** [comment] 2015-09-25 17:27
When I say internal, I mean that the user never has to know about the `instance` prop unless their initializers use it. The current instance gets bound to every initializer, so you would use `this` most of the time. I'm a little hazy on the use cases for the `instance` prop, hopefully @ericelliott or @koresar can help with that.

**Comment by markokr** [comment] 2015-09-25 18:02
well, thats my point - why is it there at all?   it's premature complexity.  i mean the while second attr as magic object.

**Comment by ericelliott** [comment] 2015-09-25 20:02
@troutowicz @markokr

We pass the real instance (not just the parameter argument) as *both* `this` *and* `arg2.instance`. It costs us nothing, and adds API consistency -- meaning that **you can see everything that is used inside the function just by looking at the function signature**, which may provide some static analysis benefits in the future.

`this` is a more implicit style. Some people prefer not to use `this` at all.

We also pass `options.instance`, which is the actual argument passed into the stamp by the stamp user.

Of course, this will be clarified more in the reference implementation. We may also need to clarify these points in the spec.

The second argument provides an extensibility point for the specification without the danger of collisions with stamp options properties. This has been discussed in depth [in another thread](https://github.com/stampit-org/stamp-specification/issues/26), which eventually led to this revised signature.

**Comment by koresar** [comment] 2015-09-26 00:05
@markokr I would agree this is a duplication. Eric has just explained the need for it. From my perspective the argument is more readable.

Elso, in ES6 the fat arrow binds the context. Consider this:
```js
compose({init(options, {instance}) => {
  console.log(insance); // prints something
  console.log(this); // prints something different
})();
```
I'd like to tuse both: ES6 features and stamps. :)

**Comment by ericelliott** [comment] 2015-09-26 00:16
Closing because we're aware of the duplication, and it's by design. Feel free to keep discussing if you like. =)

**Closed by ericelliott** 2015-09-26 00:16 UTC
Labels: wontfix

**Comment by markokr** [comment] 2015-09-26 13:43
Ok, in any case current api is better than magic properties in options.  And the fat-arrow point is also good.
